const fallbackCategories = [
  {
    _id: 'category-electronics',
    name: 'Electronics',
    slug: 'electronics',
    image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    productCount: 3,
  },
  {
    _id: 'category-fashion',
    name: 'Fashion',
    slug: 'fashion',
    image_url: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    productCount: 2,
  },
  {
    _id: 'category-home',
    name: 'Home',
    slug: 'home',
    image_url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    productCount: 2,
  },
]

const fallbackProducts = [
  {
    _id: 'product-1',
    name: 'Wireless Headphones',
    slug: 'wireless-headphones',
    description: 'Immersive audio with noise cancellation.',
    price: 89.99,
    stock: 15,
    category_id: 'category-electronics',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
    is_deleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'product-2',
    name: 'Smart Watch',
    slug: 'smart-watch',
    description: 'Track fitness, notifications, and more.',
    price: 129.99,
    stock: 9,
    category_id: 'category-electronics',
    images: ['https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80'],
    is_deleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'product-3',
    name: 'Laptop Sleeve',
    slug: 'laptop-sleeve',
    description: 'Protect your device with this padded sleeve.',
    price: 34.5,
    stock: 20,
    category_id: 'category-electronics',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80'],
    is_deleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'product-4',
    name: 'Classic Denim Jacket',
    slug: 'classic-denim-jacket',
    description: 'A timeless jacket for everyday wear.',
    price: 59.0,
    stock: 12,
    category_id: 'category-fashion',
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'],
    is_deleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'product-5',
    name: 'Leather Tote Bag',
    slug: 'leather-tote-bag',
    description: 'Stylish and spacious for your essentials.',
    price: 74.5,
    stock: 8,
    category_id: 'category-fashion',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
    is_deleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'product-6',
    name: 'Ceramic Vase',
    slug: 'ceramic-vase',
    description: 'A modern accent piece for your home.',
    price: 24.99,
    stock: 14,
    category_id: 'category-home',
    images: ['https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=800&q=80'],
    is_deleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'product-7',
    name: 'Scented Candle Set',
    slug: 'scented-candle-set',
    description: 'Relaxing candles for a cozy atmosphere.',
    price: 18.75,
    stock: 18,
    category_id: 'category-home',
    images: ['https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=800&q=80'],
    is_deleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const getFallbackProducts = () => fallbackProducts.map((product) => ({ ...product }))
export const getFallbackCategories = () => fallbackCategories.map((category) => ({ ...category }))
export const getFallbackUser = () => ({
  _id: 'demo-user',
  name: 'Demo User',
  email: 'demo@kosheli.local',
  role: 'user',
  isGuest: false,
})
